import {DarkTheme, DefaultTheme} from '@react-navigation/native';

export const darkTheme = {
  ...DarkTheme,

  mode: 'dark',

  colors: {
    ...DarkTheme.colors,
    background: 'black',
    PRIMARY_BACKGROUND_COLOR: '#0F0F0F',
    SECUNDARY_BACKGROUND_COLOR: '#3E3E3E',
    PRIMARY_TEXT_COLOR: '#ffffff',
    PRIMARY_BUTTON_COLOR: '#23a8d9',
    PRIMARY_BUTTON_TEXT_COLOR: '#ffffff',
    STATUS_BAR_STYLE: 'light-content',
    FONTAWESOME_ICON_COLOR: '#fff',
    TEMPLATE_BACKGROUND_COLOR: '#000',
    DIRECTION_ICON_COLOR: '#fff',
    MODAL_BACKGROUND_COLOR: '#000',
    GALIPOVAC_BACKGROUND_COLOR: '#000',
    GREEN_LAKE_BACKGROUND_COLOR: '#000',
    SV_JURE_BACKGROUND_COLOR: '#000',
    GREEN_CATHEDRAL_BACKGROUND_COLOR: '#000',
    BADNJEVICE_BACKGROUND_COLOR: '#000',
    DVA_OKA_BACKGROUND_COLOR: '#000',
    TEXT_COLOR: '#fff',
    DIALOG_BUTTON_COLOR: '#fff',
    EVENT_BACKGROUND_COLOR: '#000',
    TOPANA_BACKGROUND_COLOR: '#000',
  },
};

export const lightTheme = {
  ...DefaultTheme,

  mode: 'light',

  colors: {
    ...DefaultTheme.colors,
    background: 'white',
    PRIMARY_BACKGROUND_COLOR: '#1F83BB',
    SECUNDARY_BACKGROUND_COLOR: 'white',
    PRIMARY_TEXT_COLOR: '#212121',
    PRIMARY_BUTTON_COLOR: '#8022d9',
    PRIMARY_BUTTON_TEXT_COLOR: '#ffffff',
    STATUS_BAR_STYLE: 'default',
    FONTAWESOME_ICON_COLOR: '#000',
    TEMPLATE_BACKGROUND_COLOR: '#CA9A8C',
    DIRECTION_ICON_COLOR: 'blue',
    MODAL_BACKGROUND_COLOR: '#fff',
    GALIPOVAC_BACKGROUND_COLOR: 'rgb(126,150,85)',
    GREEN_LAKE_BACKGROUND_COLOR: '#6ba4a1',
    SV_JURE_BACKGROUND_COLOR: '#7d8572',
    GREEN_CATHEDRAL_BACKGROUND_COLOR: '#a69244',
    BADNJEVICE_BACKGROUND_COLOR: '#adbab3',
    DVA_OKA_BACKGROUND_COLOR: '#866926',
    TEXT_COLOR: '#000',
    DIALOG_BUTTON_COLOR: '#1F83BB',
    EVENT_BACKGROUND_COLOR: '#BB22AC',
    TOPANA_BACKGROUND_COLOR: '#7d8572',
  },
};
